---
name: Test Code

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
  schedule:
    - cron: '12 23 7 * *'
jobs:
  build:
    env:
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        perl: ['5.40', '5.38', '5.36', '5.34', '5.32', '5.30', '5.28', '5.22']
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - name: Install Dependencies
        run: |
          cpanm -iqn --skip-satisfied File::Spec ExtUtils::MakeMaker
          cpanm -iqn --skip-satisfied Test::Pod::Spelling::CommonMistakes
          cpanm -iqn --skip-satisfied Test::Portability::Files Test::Carp
          cpanm -iqn --skip-satisfied --installdeps --notest .
      - name: Make Module
        run: |
          # find . -name build.log | xargs cat
          perl Makefile.PL
          make
        env:
          AUTHOR_TESTING: 1
          AUTOMATED_TESTING: 1
      - name: Run Tests
        run: prove -l -b t
        env:
          AUTHOR_TESTING: 1
          AUTOMATED_TESTING: 1
